### ISSUE TITLE
NumLock (KBD_NUM?) setting not reported

### ISSUE THREAD

**Issue by capehill** [AmigaPorts/SDL#16]
Originally reported here https://github.com/AmigaPorts/SDL/issues/195

**Comment by raziel-** [comment]
I don't understand...do I have to redo my issue report, or is it sufficient to link to the outdated tracker?

I'm adding the posts here, better safe than sorry

[](https://github.com/raziel-)Comments
@[raziel-](https://github.com/raziel-) raziel- commented [29 days ago](https://github.com/AmigaPorts/SDL/issues/195#issue-1167297525)
See also here: https://github.com/scummvm/scummvm/pull/3329?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDIzNTQwOTMwNDY6Nzk5OTIz&notifications_query=repo%3Ascummvm%2Fscummvm#issuecomment-1065886198[](https://github.com/raziel-)

TL;DR

SDL never reports the numlock to be on.

So that would be a bug/unimplemented feature on my platforms SDL2 implementation?

Yes. Or a design decision.

@[raziel-](https://github.com/raziel-) raziel- commented [28 days ago](https://github.com/AmigaPorts/SDL/issues/195#issuecomment-1066137074)
followup

The NumLock key itself doesn't produce a RAWKEY event, but the key presses on the numpad keys do, with different values according to the NumLock state.

(This info is taken from the "learning" mode of http://os4depot.net/function=showfile&file=utility/misc/allkeys.lha)

So, i think the way to go is to check for those RAWKEY codes and use them to distinguish between if numlock is in use or not and report that instead of a "global" numlock setting.

Here are all the RAWKEY combinations from Allkeys for the NumPad keys.

NumLock ON

$8100000F - RAWKEY - NumPad + 0 and
$8100008F - RAWKEY - NumPad + 0 (upstroke)
$8100003C - RAWKEY - NumPad + , and
$810000BC - RAWKEY - NumPad + , (upstroke)
$81000043 - RAWKEY - NumPad + Enter and
$810000C3 - RAWKEY - NumPad + Enter (upstroke)
$8100001D - RAWKEY - NumPad + 1 and
$8100009D - RAWKEY - NumPad + 1 (upstroke)
$8100001E - RAWKEY - NumPad + 2 and
$8100009E - RAWKEY - NumPad + 2 (upstroke)
$8100001F - RAWKEY - NumPad + 3 and
$8100009F - RAWKEY - NumPad + 3 (upstroke)
$8100002D - RAWKEY - NumPad + 4 and
$810000AD - RAWKEY - NumPad + 4 (upstroke)
$8100002E - RAWKEY - NumPad + 5 and
$810000AE - RAWKEY - NumPad + 5 (upstroke)
$8100002F - RAWKEY - NumPad + 6 and
$810000AF - RAWKEY - NumPad + 6 (upstroke)
$8100005E - RAWKEY - NumPad + + and
$810000DE - RAWKEY - NumPad + + (upstroke)
$8100003D - RAWKEY - NumPad + 7 and
$810000BD - RAWKEY - NumPad + 7 (upstroke)
$8100003E - RAWKEY - NumPad + 8 and
$810000BE - RAWKEY - NumPad + 8 (upstroke)
$8100003F - RAWKEY - NumPad + 9 and
$810000BF - RAWKEY - NumPad + 9 (upstroke)
$8100005C - RAWKEY - NumPad + / and
$810000DC - RAWKEY - NumPad + / (upstroke)
$8100005D - RAWKEY - NumPad + * and
$810000DD - RAWKEY - NumPad + * (upstroke)
$8100004A - RAWKEY - NumPad + - and
$810000CA - RAWKEY - NumPad + - (upstroke)

NumLock OFF

$81000047 - RAWKEY - NumPad + Insert and
$8100008F - RAWKEY - NumPad + 0 (upstroke)
$81000046 - RAWKEY - NumPad Del , and
$810000BC - RAWKEY - NumPad + , (upstroke)
$81000043 - RAWKEY - NumPad + Enter and
$810000C3 - RAWKEY - NumPad + Enter (upstroke)
$81000071 - RAWKEY - NumPad + End and
$8100009D - RAWKEY - NumPad + 1 (upstroke)
$8100004D - RAWKEY - NumPad + Cursor Down and
$8100009E - RAWKEY - NumPad + 2 (upstroke)
$81000049 - RAWKEY - NumPad + PageDown and
$8100009F - RAWKEY - NumPad + 3 (upstroke)
$8100004F - RAWKEY - NumPad + Cursor Left and
$810000AD - RAWKEY - NumPad + 4 (upstroke)
$8100002E - RAWKEY - NumPad + 5 and
$810000AE - RAWKEY - NumPad + 5 (upstroke)
$8100004E - RAWKEY - NumPad + Cursor Right and
$810000AF - RAWKEY - NumPad + 6 (upstroke)
$8100005E - RAWKEY - NumPad + + and
$810000DE - RAWKEY - NumPad + + (upstroke)
$81000070 - RAWKEY - NumPad + Home and
$810000BD - RAWKEY - NumPad + 7 (upstroke)
$8100004C - RAWKEY - NumPad + Cursor Up and
$810000BE - RAWKEY - NumPad + 8 (upstroke)
$81000048 - RAWKEY - NumPad + PageUp and
$810000BF - RAWKEY - NumPad + 9 (upstroke)
$8100005C - RAWKEY - NumPad + / and
$810000DC - RAWKEY - NumPad + / (upstroke)
$8100005D - RAWKEY - NumPad + * and
$810000DD - RAWKEY - NumPad + * (upstroke)
$8100004A - RAWKEY - NumPad + - and
$810000CA - RAWKEY - NumPad + - (upstroke)

**Comment by capehill** [comment]
@raziel-  Could you please check the current status?

**Comment by raziel-** [comment]
I can't check the original state in ScummVM.
It **has** been fixed since then there.

So i guess this bug report is obsolete?

**Comment by capehill** [comment]
Ok, closing this one. Thanks!
